apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-limit-range
  labels:
    app.kubernetes.io/name: default-cpu-limit-range
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: 0.1
    type: Container
