apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/kibana.deployment.yaml
- resources/kibana.service.yaml

configMapGenerator:
- name: kibana-config
  options:
    labels:
      app.kubernetes.io/name: kibana-config
  files:
  - config/kibana.yml

commonLabels:
  app.kubernetes.io/instance: default

# These labels will not be added to Selector
transformers:
- |-
  apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: commonLabelsNoSelector
  labels:
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: search
    app.kubernetes.io/part-of: kibana
    app.kubernetes.io/managed-by: kustomize
  fieldSpecs:
  - path: metadata/labels
  - path: spec/template/metadata/labels
