apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: localhost:5000/elasticsearch:0.0.1
        ports:
          - containerPort: 9200
            name: http
          - containerPort: 9300
            name: transport
        volumeMounts:
        - name: config
          mountPath: /etc/elasticsearch/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /etc/elasticsearch/log4j2.properties
          subPath: log4j2.properties
        - name: data
          mountPath: /usr/share/elasticsearch/data
        envFrom:
        - configMapRef:
            name: elasticsearch-env
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DISCOVERY_SEED_HOSTS
          value: "$(NAMESPACE)-elasticsearch.$(NAMESPACE).svc.cluster.local"
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 90
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
      securityContext:
        fsGroup: 101
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
