apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibana
    spec:
      containers:
      - name: kibana
        image: localhost:5000/kibana:0.0.1
        ports:
          - containerPort: 5601
            name: kibana
        volumeMounts:
        - name: config
          mountPath: /etc/kibana/kibana.yml
          subPath: kibana.yml
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_HOSTS
          value: "https://$(NAMESPACE)-elasticsearch.$(NAMESPACE).svc.cluster.local:9200"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=512"
        readinessProbe:
          tcpSocket:
            port: kibana
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: kibana
          initialDelaySeconds: 30
          periodSeconds: 90
      volumes:
      - name: config
        configMap:
          name: kibana-config
      securityContext:
        fsGroup: 101
